### PR TITLE
Added api call to get storage charges for bp

### PR DESCRIPTION
**Pull request by mbeynon**
Add python call for the existing API call.

### CODE REVIEW

**Comment by gilhoffer** [comment]
Thanks @yotam-sela-ravello , on top of it @mbeynon, I'm not sure this call does what you think it does - in the commit comment you've wrote 

> Added api call to get storage charges for bp

when in practice this call gets the estimated hourly charge for the runtime of an application created out of this blueprint (compute + disk storage + public IPs).

**Comment by mbeynon** [comment]
@yotam-sela-ravello - thank you for the feedback.  I modeled the call after the same for applications.  In my use of this call, I always use deployment_options with an optimizationLevel.  Can easily change to always error if nothing passed in.  There was no documentation for the call, so I infered semantics by trial and error.

How do we proceed?  Are you asking me to revise the code for these two points and submit another PR?

@gilhoffer - I was told in Dec 2016 that this call would return the size of the actual blueprint library storage size.  Is there a difference between the bp size and an application created out of it?  If this API call is not appropriate, how then can I get the library blueprint size that we need to apportion monthly recurring storage costs across all objects (applications, blueprints, images) and group by the cost center?

**Comment by gilhoffer** [comment]
Yes, please revise and send another PR.
We will also update the docs for this call.

I'm not sure who told you that this is what the call does - it  doesn't, I'm sorry about that.
Library cost can in many cases be shared across many library items (e.g. if a blueprint/vm is just a small change from another blueprint/vm in your lib, the real incremental cost for this BP/vm can vary greatly) and can change unexpectedly when another item is deleted.

I'll ask our product management ( @itsikmusseri ) to reach out regrading your need.

**Comment by mbeynon** [comment]
Our cost allocation approach uses the distinction between logical size of an object and the actual size of an object in the library after deduplication is applied.  We compute what part of the aggregate logical disk size an object uses and assign the total storage cost proportionally.  Not perfect, but seems to be the best we can do.  I will work with project management ( @itsikmusseri  ) to see if there's a better way.

**Comment by mbeynon** [comment]
All changes have been made, please review.

**Comment by hadard** [comment]
Thanks Mike!

**Pull request merged**
