### PR TITLE
sdk: add reset_disks_vm()

### PR DESCRIPTION
**Pull request by ryran**
Hey folks. Here's another one.
Not sure how you would want this to be named ... I suspect you won't like the capital `D` but I wasn't sure what else to do. (`/applications/:appId/vms/:vmId/resetDisks`)

### CODE REVIEW

**Comment by zoza** [comment]
maybe to just call reset_disks ???

**Comment by ryran** [comment]
> maybe to just call reset_disks ???

All the other vm calls are `<SOMETHING>_vm` but yeah that's up to you guys. Say the word and I'll rename it.

**Comment by gilhoffer** [comment]
Please name it `reset_disks_vm` and I'll merge the change.

**Comment by ryran** [comment]
Done.

**Comment by gilhoffer** [comment]
thanks @ryran , merged.

**Pull request merged**
