### PR TITLE
Add invite_user(user) call

### PR DESCRIPTION
**Pull request by bostrick**
Although __doc__ of preceding create_user() call made it sound like it
would invite a user, feeding it a parameter dict as discussed in Ravello
API docs returns a HTTP 500, and the URL seems misaligned from the
API docs. invite_user() has the intended behavior, without trying to
address apparent shortcomings of create_user().

### CODE REVIEW

**Comment by gilhoffer** [comment]
@yotam-sela-ravello , @hadard any reason not to remove the old/deprecated call (POST /organizations/{id}/users) from the SDK?

**Comment by yotam-sela-ravello** [comment]
@gilhoffer we should remove it's legacy code

**Comment by gilhoffer** [comment]
@yotam-sela-ravello , cool, so can you please merge/accept the PR from @bostrick and remove the old call (should take no more than 10 minutes ;) ).

**Comment by hadard** [comment]
Thanks @bostrick! merged it to master

**Comment by bostrick** [comment]
Thanks all!

**Pull request merged**
