### PR TITLE
Fix for the disconnections issue and vnc issue

### PR DESCRIPTION
**Pull request by elayeek**
Now uses a persistent session which saves the cookies.
Also, fixed the get_vnc_url

### CODE REVIEW

**Comment by ryran** [comment]
```
[rsaw:tmp]$ git clone https://github.com/elayeek/python-sdk.git
Cloning into 'python-sdk'...
remote: Counting objects: 468, done.
remote: Compressing objects: 100% (194/194), done.
remote: Total 468 (delta 251), reused 462 (delta 249)
Receiving objects: 100% (468/468), 112.15 KiB | 0 bytes/s, done.
Resolving deltas: 100% (251/251), done.

[rsaw:tmp]$ cd python-sdk/lib/

[rsaw:lib]$ python
Python 2.7.5 (default, Feb 11 2014, 07:46:25) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-13)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ravello_sdk
>>> u = 'xxxx'
>>> p = 'xxxx'
>>> r = ravello_sdk.RavelloClient()
>>> r.login(u, p)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ravello_sdk.py", line 284, in login
    self._login()
  File "ravello_sdk.py", line 295, in _login
    response = self._request('POST', '/login', b'', headers)
  File "ravello_sdk.py", line 344, in _request
    response = self._connection.send(self._connection.prepare_request(req), proxies=self._proxies,
AttributeError: 'Session' object has no attribute 'prepare_request'
```

**Comment by elayeek** [comment]
When did you do that?
Because not only does it work for me (just tried it) but also, when looking at the repository it seems that the line numbers displayed are different than where it is in my repository.

https://github.com/elayeek/python-sdk/blob/master/lib/ravello_sdk.py

**Comment by ryran** [comment]
I posted he comment literally right after running those commands.

**Comment by elayeek** [comment]
Which version of requests do you have installed? It seems 'prepare_request' was only added at version 2.0 (If that's the case then it seems there is a more backwards compatible solution but just want to be sure)

**Comment by ryran** [comment]
> *It seems 'prepare_request' was only added at version 2.0*

Ah. I see. At the moment I'm on a RHEL7 box so 1.1.0.

**Comment by elayeek** [comment]
Ok, so that seems to be it and I will also look into making it more backwards compatible.

**Comment by ryran** [comment]
Don't do it just for me!

My unsolicited advice: consider whether the new non-backwards-compatible code is better for the users in a practical way -- e.g., does it actually enhance the user experience in noticeable ways or is it just so you can write efficient/fancy/elegant/pythonic code?

If the latter, I hope you'll reconsider. While people like me can always download a newer version of a required module, it would be a bummer to do that for every single RHEL7 deployment.

**Comment by elayeek** [comment]
I Agree.
I made the assumption that the package would be installed the "normal" way and then it could simply be set as a dependency (with a minimum version) to force pip to upgrade requests as it installs. It seems that this assumption is somewhat lenient when considering the pace we've been adding things and so I've changed the problematic section to something that should work with requests version 1.1.0

**Comment by ryran** [comment]
```
[rsaw:tmp]$ date
Fri Feb 13 00:31:01 EST 2015

[rsaw:tmp]$ git clone https://github.com/ravello/python-sdk.git master
Cloning into 'master'...
remote: Counting objects: 453, done.
remote: Total 453 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (453/453), 108.91 KiB | 0 bytes/s, done.
Resolving deltas: 100% (243/243), done.

[rsaw:tmp]$ cp -v master/lib/ravello_sdk.py .
‘master/lib/ravello_sdk.py’ -> ‘./ravello_sdk.py’

[rsaw:tmp]$ cat ravtest.py 
from getpass import getpass
import ravello_sdk
u = raw_input("Username: ")
p = getpass("Password: ")
r = ravello_sdk.RavelloClient()
r.login(u, p)
apps = r.get_applications()
print("len(get_applications()): {}".format(len(apps)))

[rsaw:tmp]$ python ravtest.py
Username: rsaw@redhat.com
Password: 
len(get_applications()): 129

[rsaw:tmp]$ git clone https://github.com/elayeek/python-sdk.git elayeek
Cloning into 'elayeek'...
remote: Counting objects: 472, done.
remote: Compressing objects: 100% (194/194), done.
remote: Total 472 (delta 253), reused 472 (delta 253)
Receiving objects: 100% (472/472), 114.11 KiB | 0 bytes/s, done.
Resolving deltas: 100% (253/253), done.

[rsaw:tmp]$ cp -v elayeek/lib/ravello_sdk.py .
‘elayeek/lib/ravello_sdk.py’ -> ‘./ravello_sdk.py’

[rsaw:tmp]$ python ravtest.py 
Username: rsaw@redhat.com
Password: 
Traceback (most recent call last):
  File "ravtest.py", line 7, in <module>
    apps = r.get_applications()
  File "/tmp/ravello_sdk.py", line 468, in get_applications
    apps = self.request('GET', '/applications')
  File "/tmp/ravello_sdk.py", line 326, in request
    response = self._request(method, path, body, headers)
  File "/tmp/ravello_sdk.py", line 405, in _request
    raise RavelloError('maximum number of retries reached')
ravello_sdk.RavelloError: maximum number of retries reached
```

**Comment by elayeek** [comment]
Small update - It seems that the older versions of requests are slightly slower but I think the timeout can be solved.
I still need to test it but it seems that a possible reason for the fact that I've been missing those problems was because I was using a strong computer which made up for it. Going to test it with a different system to verify.

**Pull request merged**
