### PR TITLE
add aspect parameter to Ravello_client.get_app() and get_vm()

### PR DESCRIPTION
**Pull request by ryran**
See http://www.ravellosystems.com/developers/rest-api/applications and http://www.ravellosystems.com/developers/rest-api/applications

### CODE REVIEW

**Comment by ryran** [comment]
Is there anything you all would like me to change here before you consider merging this?

**Comment by gilhoffer** [comment]
Hi Ryan, sorry for the delay, we are somewhat swamped (you will see what we've been hard working on next week ;) ).
We'll do our best to review and merge this (as well as the other open pull requests) next week.

**Comment by ryran** [comment]
@gilhoffer: Thanks for the response! Look forward to seeing what you guys have been cooking. :)

**Comment by hadard** [comment]
Looks good!

**Pull request merged**
